#filehandle=open("filename","r or w or a")
#read()   read(integer#no of char to read)  readline()  readlines()   seek()
#write() writeline('....\n') writelines([list of lines])
# flush() close()    
x=open("filename","+w")
x.writelines("hi hello")
x.writelines("world")
x.flush()
x.seek(0)
y=x.read(5)
print(y)